apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: "https://localhost:8080"
  project: default
  source:
    path: applications
    repoURL: "https://github.com/mishraom05/argocd-experiments.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - createNamespace=true